version: "3.8"

services:
  agroclima:
    build:
      context: .
      dockerfile: DockerFile
    image: agroclima:latest
    container_name: agroclima
    restart: unless-stopped
    ports:
      - "8097:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      NEXT_PUBLIC_APP_URL: "https://agroclima.agroptimum.com"
