version: "3.8"

services:
  web:
    container_name: agroclima-web
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8097:3000"

    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}

    restart: unless-stopped
